---
    language: python
    
    env:
      global:
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "f682F4xdwl9gYQTeaiSMVE/3AQcv75L66wJtE1jXGyluoFAR6vi4uHH+RulInHf8IGDyM+Vct8ed07eFXA8xNdaxnhivxEA9DvROpZ/6TzMDIiGgxEdw927bazAI/Ey2w44Nni4NIPYZ9kWNmyKNvdf6A81L3M1iHk/XRqQuvkPuoFqG07z0TWc0K+WW3CbDPAivuN1nEUdvBpeX5E5xdEHZeictTwnozyYkfeJUYeDLCIib8NSEQwIl/7NRXFTmDsaO5f/KE89v2WxW7Lq0OYrx5lIq2LSuznjCefck5kWSvw+xNgevUXcZxRh8PZhp42fpH5VXGwgSFdZJqTvAAaLVucpoeyCTJciQKL6Fhb9+fX78vEGI3aF7P1m43EHksCc749L+UgAmuwCi6LEmdkyuxq2YSdGwA0xFbOuF40Oq2SBcbJXrhP2WhSMOTV7VZys8p4o7Y3d1QDQi351OUIA0BVl+t9neHMRqsbHCyJVKhrPMFXZWQY0YxKPPpHai2ADyqGpAD8ffoIVm7g6YpYsqtx08UhEZ6AkXC6H4hLGJlSYI9502JoKCxIkdq1qssssyF4ZHlXAvsL8jvcFNLTudGaTpjbm05L3mcCmKXdEG+sZ7tVkvSYBiAekD1hUJNCL8oZ3tVp78Z7T0TQPQ7wWaJ9pPLJJS6LfGwyrSQHw="   # yamllint disable-line
    
    matrix:
      include:
        - python: '3.6'
          install:
            - pip install -r requirements.txt
            - pip install -r requirements-dev.txt --no-cache-dir
            - pip install codecov
          script:
            - black --check .
            - isort -c -rc .
            - flake8
            - py.test --cov=./ --color=yes
          after_success:
            - codecov
    
        - python: '3.6'
          sudo: required
          dist: trusty
          services:
            - docker
          env:
            - IMAGE_NAME=praekeltfoundation/ge-messaging-consent:develop
          before_script:
            - docker pull "$IMAGE_NAME" || true
          script:
            - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
          before_deploy:
            - pip install docker-ci-deploy==0.3.0
            - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin   # yamllint disable-line
          deploy:
            provider: script
            script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"   # yamllint disable-line
            on:
              branch: develop
          install: []
          addons: {}
        - python: '3.6'
          sudo: required
          dist: trusty
          services:
            - docker
          env:
            - IMAGE_NAME=praekeltfoundation/gp-messaging-consent
          before_script:
            - docker pull "$IMAGE_NAME" || true
          script:
            - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
          before_deploy:
            - pip install docker-ci-deploy==0.3.0
            - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin   # yamllint disable-line
          deploy:
            provider: script
            script: dcd --version "$(git tag -l --points-at HEAD)" --version-semver --version-latest "$IMAGE_NAME"   # yamllint disable-line
            on:
              tags: true
          install: []
          addons: {}